package com.alevel.compsci.advay.studentselector.repository;

import com.alevel.compsci.advay.studentselector.entity.Event;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * Interface extended JPARepository where Event is the entity and Integer is the autogenerated ID
 * JpaRepository already has most commonly used methods defined.
 */
public interface EventRepository extends JpaRepository<Event, Integer> {

    List<Event> findAllByEventTitle(String eventTitle);

    List<Event> findAllByOrganiserID(int organiserID);

    void deleteByOrganiserID(int organiserID);
}
