package com.alevel.compsci.advay.studentselector.repository;

import com.alevel.compsci.advay.studentselector.entity.Subscription;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * Interface extended JPARepository where Event is the entity and Integer is the autogenerated ID
 * JpaRepository already has most commonly used methods defined.
 */
public interface SubscriptionRepository extends JpaRepository<Subscription, Integer> {

    List<Subscription> findAllByEventID(int eventID);

    List<Subscription> findAllByUserID(int userID);

    void deleteByUserID(int userID);
}