package com.alevel.compsci.advay.studentselector.repository;


import com.alevel.compsci.advay.studentselector.entity.AppUser;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Interface extended JPARepository where Event is the entity and Integer is the autogenerated ID
 * JpaRepository already has most commonly used methods defined.
 */
public interface UserRepository extends JpaRepository<AppUser, Integer> {

    AppUser findAllByUsername(String username);


}
